# MultiDevice Data Usage 

This notebook explains how to use this repo's multidevice etl pipeline, and then how to use the processed data to view and retrieve for each device (`device_type`, `device_id`), its dataframes (`df`); and each df's variables (AKA columns).

## Load All Data

The function `load_data()` automatically triggers the etl (extract, transform, load) pipeline to prepare all available device data for analysis. 
This is the one-liner command to load everything. 

**Note**: This pipeline is currently extracts from a mounted Proton Drive folder, it can be upgraded to API calls per `device_id` instead.

In [1]:
import sys
sys.path.insert(0, "..") # run at repo root

from src.etl.load import load_data

MOUNT_PATH = "/home/yul/mnt/proton-data"

data = load_data(MOUNT_PATH)

--- Scanning: /home/yul/mnt/proton-data ---
Processing folder: Atmotube
   ✅ Loaded C3CBE16AE294_01-May-2026_12-Jun-2026: (18241, 22)
   ✅ Loaded C7A595F09965_01-May-2026_12-Jun-2026: (11817, 22)
   ✅ Loaded CC6A51B6DC90_01-May-2026_12-Jun-2026: (12068, 22)
   ✅ Loaded DB7A737B8CA0_01-May-2026_12-Jun-2026: (17253, 22)
   ✅ Loaded E53CDF6B7FD3_01-May-2026_12-Jun-2026: (12250, 22)
   ✅ Loaded E9F716D1DF7B_01-May-2026_12-Jun-2026: (24095, 22)
   ✅ Loaded FD20113AFE41_01-May-2026_12-Jun-2026: (12990, 22)
  ✅ Atmotube: 7 device_id(s) loaded
Processing folder: Fitbit
  ⚠️ Fitbit: No valid CSVs loaded
Processing folder: Ponyopi
  ⚠️ Ponyopi: No valid CSVs loaded
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/C3CBE16AE294_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/C7A595F09965_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/CC6A51B6DC90_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/DB7A737B8CA0_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/E53CDF6B7FD3_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/E9F716D1DF7B_01-May-2026_12-Jun-2026
Detected datetime column: 'Date (UTC+05:30)' (score: 5.00) → renamed to 'datetime'
Detected lat column: 'Latitude' → renamed to 'latitude'
Detected lon column: 'Longitude' → renamed to 'longitude'
No raw particle count data available.
No satellite data available.
✅ Transformed Atmotube/FD20113AFE41_01-May-2026_12-Jun-2026

In [2]:
# See which device types are available 
list_device_types = data.keys() 
print(list_device_types)

# See available device IDs, per type
list_device_ids = data["Atmotube"].keys()
print(list_device_ids)

dict_keys(['Atmotube'])
dict_keys(['C3CBE16AE294_01-May-2026_12-Jun-2026', 'C7A595F09965_01-May-2026_12-Jun-2026', 'CC6A51B6DC90_01-May-2026_12-Jun-2026', 'DB7A737B8CA0_01-May-2026_12-Jun-2026', 'E53CDF6B7FD3_01-May-2026_12-Jun-2026', 'E9F716D1DF7B_01-May-2026_12-Jun-2026', 'FD20113AFE41_01-May-2026_12-Jun-2026'])

In [ ]:
# Alternatively, this is how to extract the raw, unprocessed data
from src.etl.extract import extract_raw_data

raw = extract_raw_data("/home/yul/mnt/proton-data")
raw["Atmotube"]["C3CBE16AE294_01-May-2026_12-Jun-2026"]  # example

## View Available Devices

For each device type (`device_type`), the actual devices are indexed according to its device ID (`device_id`). 

The function `skim()` quickly shows the available dataframes (`df`) per actual device (`device_id`).

It returns, per each available device, its shape (columns nos. and rows nos.) and range (start datetime to end datetime).

In [3]:
from src.utils import skim

# a. View ALL of the loaded available data, devices, and device types
# skim(data) 

# b. View loaded available data of a device type
# skim(data, "Atmotube") 

# c. View loaded avail data of a specific device ID
skim(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026") # add "pm" after device_id to look for a specific df

# (equivalent manual version, for comparison:)
# display_loaded_data({"Atmotube": {"C3CBE16AE294_01-May-2026_12-Jun-2026": data["Atmotube"]["C3CBE16AE294_01-May-2026_12-Jun-2026"]}})

Atmotube/C7A595F09965_01-May-2026_12-Jun-2026
  dfs : ['gis', 'pm', 'weather', 'gas', 'phone', 'sat', 'txt']
  gis       : (11817, 5)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  pm        : (11817, 4)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  weather   : (11817, 5)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  gas       : (11817, 5)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  phone     : (11817, 6)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  sat       : (11817, 2)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00
  txt       : (11817, 2)  |  2026-05-30 14:57:00+00:00 → 2026-06-12 15:56:00+00:00

The same function `skim()` can also be used more specifically by quickly insepecting one dataframe (`df`). 
It returns, of the specified df, every available variable's (AKA columns) row length and data type (aka dtype)

In [4]:
skim(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026", "pm")

Atmotube/C7A595F09965_01-May-2026_12-Jun-2026/pm
  df.shape: (11817, 4)
  datetime                 : (11817, datetime64[ns, UTC])
  pm1_0_ugm3_atm           : (11817, float64)
  pm2_5_ugm3_atm           : (11817, float64)
  pm10_ugm3_atm            : (11817, float64)

                       datetime  pm1_0_ugm3_atm  pm2_5_ugm3_atm  pm10_ugm3_atm
0     2026-05-30 14:57:00+00:00            16.3            17.1           17.1
1     2026-05-30 14:58:00+00:00            14.8            15.6           15.6
2     2026-05-30 14:59:00+00:00            15.6            16.4           16.4
3     2026-05-30 15:00:00+00:00            14.7            15.4           15.4
4     2026-05-30 15:01:00+00:00            17.5            18.4           18.4
...                         ...             ...             ...            ...
11812 2026-06-12 15:52:00+00:00            27.9            29.2           29.2
11813 2026-06-12 15:53:00+00:00            28.7            30.1           30.1
11814 2026-06-12 15:54:00+00:00            27.2            28.5           28.5
11815 2026-06-12 15:55:00+00:00            26.5            27.8           27.8
11816 2026-06-12 15:56:00+00:00            26.5            27.9           28.0

[11817 rows x 4 columns]

In [5]:
skim(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026", "pm", "pm10_ugm3_atm")

Atmotube/C7A595F09965_01-May-2026_12-Jun-2026/pm/pm10_ugm3_atm
  (11817, float64)

### Structural Relationship of the Data 

Below represents the structural hierarchical relationship between the data based on device type, devices, and each device's dataframes and their variables. 

They are all retrievable as a dictionary of each other.

In [6]:
import json

# Structure of the entire data hierarchy
print("Available Device Types:")
print(json.dumps({k: type(v).__name__ for k, v in data.items()}, indent=2))

print("\nDevices in Atmotube:")
print(json.dumps({k: type(v).__name__ for k, v in data["Atmotube"].items()}, indent=2))

from src.utils import get
device = get(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026")

print("\nStructure of one Device:")
print(json.dumps({k: type(v).__name__ for k, v in device.items()}, indent=2))

Available Device Types:
{
  "Atmotube": "dict"
}

Devices in Atmotube:
{
  "C3CBE16AE294_01-May-2026_12-Jun-2026": "dict",
  "C7A595F09965_01-May-2026_12-Jun-2026": "dict",
  "CC6A51B6DC90_01-May-2026_12-Jun-2026": "dict",
  "DB7A737B8CA0_01-May-2026_12-Jun-2026": "dict",
  "E53CDF6B7FD3_01-May-2026_12-Jun-2026": "dict",
  "E9F716D1DF7B_01-May-2026_12-Jun-2026": "dict",
  "FD20113AFE41_01-May-2026_12-Jun-2026": "dict"
}

Structure of one Device:
{
  "gis": "DataFrame",
  "pm": "DataFrame",
  "weather": "DataFrame",
  "gas": "DataFrame",
  "phone": "DataFrame",
  "sat": "DataFrame",
  "txt": "DataFrame"
}

## Retrieve Device Data

Since any device and its contents are all kept as nested dictionaries. 

The function `get()` can navigate and retrieve a device, its dataframes, and its variables (columns).

It will return  either the nested dict (for multiple devices) or flattened dict (for one device) — the returned structure is exactly how the data is being kept. 

### 1. For One or More Devices

In [20]:
from src.utils import get, use

all_devices = get(data) # This will literally get all the loaded available data, 
# print(all_devices)    # showing its implemented structure as one large nested dict

# a. Retrieve all devices of a one type (nested dict)
atmotube_devices = get(data, "Atmotube")
# print(atmotube_devices)

# b. Retrieve one device ID (flattened dict)
atmotube_device = get(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026") 
print(atmotube_device)


# (equivalent manual version, for comparison:)
# device1_pm_df = data["Atmotube"]["C3CBE16AE294_01-May-2026_12-Jun-2026"]["data"]

{'gis':                        datetime  longitude  latitude      timezone  altitude
0     2026-05-30 14:57:00+00:00        NaN       NaN          <NA>       NaN
1     2026-05-30 14:58:00+00:00   88.35042  22.50010  Asia/Kolkata       0.0
2     2026-05-30 14:59:00+00:00   88.35043  22.50008  Asia/Kolkata       0.0
3     2026-05-30 15:00:00+00:00   88.35045  22.50014  Asia/Kolkata       0.0
4     2026-05-30 15:01:00+00:00   88.35052  22.50025  Asia/Kolkata       0.0
...                         ...        ...       ...           ...       ...
11812 2026-06-12 15:52:00+00:00        NaN       NaN          <NA>       NaN
11813 2026-06-12 15:53:00+00:00        NaN       NaN          <NA>       NaN
11814 2026-06-12 15:54:00+00:00        NaN       NaN          <NA>       NaN
11815 2026-06-12 15:55:00+00:00        NaN       NaN          <NA>       NaN
11816 2026-06-12 15:56:00+00:00        NaN       NaN          <NA>       NaN

[11817 rows x 5 columns], 'pm':                        datetime  pm1_0_ugm3_atm  pm2_5_ugm3_atm  pm10_ugm3_atm
0     2026-05-30 14:57:00+00:00            16.3            17.1           17.1
1     2026-05-30 14:58:00+00:00            14.8            15.6           15.6
2     2026-05-30 14:59:00+00:00            15.6            16.4           16.4
3     2026-05-30 15:00:00+00:00            14.7            15.4           15.4
4     2026-05-30 15:01:00+00:00            17.5            18.4           18.4
...                         ...             ...             ...            ...
11812 2026-06-12 15:52:00+00:00            27.9            29.2           29.2
11813 2026-06-12 15:53:00+00:00            28.7            30.1           30.1
11814 2026-06-12 15:54:00+00:00            27.2            28.5           28.5
11815 2026-06-12 15:55:00+00:00            26.5            27.8           27.8
11816 2026-06-12 15:56:00+00:00            26.5            27.9           28.0

[11817 rows x 4 columns], 'weather':                        datetime  aqs_total  temp_c  hum_pct  press_hpa
0     2026-05-30 14:57:00+00:00         76    31.5     66.0     1004.0
1     2026-05-30 14:58:00+00:00         74    31.6     67.0     1004.0
2     2026-05-30 14:59:00+00:00         74    31.5     66.0     1004.1
3     2026-05-30 15:00:00+00:00         74    31.5     66.0     1004.1
4     2026-05-30 15:01:00+00:00         75    31.4     67.0     1004.7
...                         ...        ...     ...      ...        ...
11812 2026-06-12 15:52:00+00:00         67    31.3     66.0     1002.5
11813 2026-06-12 15:53:00+00:00         66    31.3     67.0     1002.4
11814 2026-06-12 15:54:00+00:00         68    31.3     67.0     1002.4
11815 2026-06-12 15:55:00+00:00         68    31.3     67.0     1002.4
11816 2026-06-12 15:56:00+00:00         68    31.3     66.0     1002.4

[11817 rows x 5 columns], 'gas':                        datetime  tvoc_index  tvoc_ppm  nox_index  co2_ppm
0     2026-05-30 14:57:00+00:00        99.0     0.093        1.0    691.0
1     2026-05-30 14:58:00+00:00        99.0     0.093        1.0    734.0
2     2026-05-30 14:59:00+00:00       102.0     0.095        1.0    727.0
3     2026-05-30 15:00:00+00:00       151.0     0.145        1.0    718.0
4     2026-05-30 15:01:00+00:00       182.0     0.181        1.0    706.0
...                         ...         ...       ...        ...      ...
11812 2026-06-12 15:52:00+00:00        77.0     0.071        1.0    504.0
11813 2026-06-12 15:53:00+00:00        75.0     0.070        1.0    530.0
11814 2026-06-12 15:54:00+00:00        80.0     0.074        1.0    836.0
11815 2026-06-12 15:55:00+00:00        81.0     0.076        1.0    646.0
11816 2026-06-12 15:56:00+00:00        80.0     0.074        1.0    632.0

[11817 rows x 5 columns], 'phone':                        datetime  battery_phone_pct  motion_phone_bool  \
0     2026-05-30 14:57:00+00:00                 24              False
1     2026-05-30 14:58:00+00:00                 24               True
2     2026-05-30 14:59:00+00:00                 24               True
3     2026-05-30 15:00:00+00:00                 24               True
4     2026-05-30 15:01:00+00:00                 24               True
...                         ...                ...                ...
11812 2026-06-12 15:52:00+00:00                 38              False
11813 2026-06-12 15:53:00+00:00                 38              False
11814 2026-06-12 15:54:00+00:00                 37              False
11815 2026-06-12 15:55:00+00:00                 37              False
11816 2026-06-12 15:56:00+00:00                 37              False

       gps_phone_bool  charge_phone_bool  cooldown_phone_bool
0                <NA>              False                False
1                True              False                False
2                True              False                False
3                True              False                False
4                True              False                False
...               ...                ...                  ...
11812            <NA>              False                False
11813            <NA>              False                False
11814            <NA>              False                False
11815            <NA>              False                False
11816            <NA>              False                False

[11817 rows x 6 columns], 'sat':                        datetime  position_error_m
0     2026-05-30 14:57:00+00:00               NaN
1     2026-05-30 14:58:00+00:00               9.0
2     2026-05-30 14:59:00+00:00               7.0
3     2026-05-30 15:00:00+00:00               8.0
4     2026-05-30 15:01:00+00:00               6.0
...                         ...               ...
11812 2026-06-12 15:52:00+00:00               NaN
11813 2026-06-12 15:53:00+00:00               NaN
11814 2026-06-12 15:54:00+00:00               NaN
11815 2026-06-12 15:55:00+00:00               NaN
11816 2026-06-12 15:56:00+00:00               NaN

[11817 rows x 2 columns], 'txt':                        datetime user_notes
0     2026-05-30 14:57:00+00:00        NaN
1     2026-05-30 14:58:00+00:00        NaN
2     2026-05-30 14:59:00+00:00        NaN
3     2026-05-30 15:00:00+00:00        NaN
4     2026-05-30 15:01:00+00:00        NaN
...                         ...        ...
11812 2026-06-12 15:52:00+00:00        NaN
11813 2026-06-12 15:53:00+00:00        NaN
11814 2026-06-12 15:54:00+00:00        NaN
11815 2026-06-12 15:55:00+00:00        NaN
11816 2026-06-12 15:56:00+00:00        NaN

[11817 rows x 2 columns]}

### 2. For One or More DataFrames

In [ ]:
from src.utils import get

# a. Retrieve one dataframe 
atmotube_device_pm = get(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026", ["pm"])
# print(atmotube_device_pm)

# b. Retrieve two or more dataframes 
atmotube_device_weatherpm = get(
    data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026",
    ["pm", "weather"]
)

print(atmotube_device_weatherpm.keys())  # Check what the dataframes are
print(atmotube_device_weatherpm) 

# (equivalent manual version, for comparison:)
# device1_pm_df = data["Atmotube"]["C3CBE16AE294_01-May-2026_12-Jun-2026"]["data"]["pm"]["df"]

dict_keys(['pm', 'weather'])
{'pm':                        datetime  pm1_0_ugm3_atm  pm2_5_ugm3_atm  pm10_ugm3_atm
0     2026-05-30 14:57:00+00:00            16.3            17.1           17.1
1     2026-05-30 14:58:00+00:00            14.8            15.6           15.6
2     2026-05-30 14:59:00+00:00            15.6            16.4           16.4
3     2026-05-30 15:00:00+00:00            14.7            15.4           15.4
4     2026-05-30 15:01:00+00:00            17.5            18.4           18.4
...                         ...             ...             ...            ...
11812 2026-06-12 15:52:00+00:00            27.9            29.2           29.2
11813 2026-06-12 15:53:00+00:00            28.7            30.1           30.1
11814 2026-06-12 15:54:00+00:00            27.2            28.5           28.5
11815 2026-06-12 15:55:00+00:00            26.5            27.8           27.8
11816 2026-06-12 15:56:00+00:00            26.5            27.9           28.0

[11817 rows x 4 columns], 'weather':                        datetime  aqs_total  temp_c  hum_pct  press_hpa
0     2026-05-30 14:57:00+00:00         76    31.5     66.0     1004.0
1     2026-05-30 14:58:00+00:00         74    31.6     67.0     1004.0
2     2026-05-30 14:59:00+00:00         74    31.5     66.0     1004.1
3     2026-05-30 15:00:00+00:00         74    31.5     66.0     1004.1
4     2026-05-30 15:01:00+00:00         75    31.4     67.0     1004.7
...                         ...        ...     ...      ...        ...
11812 2026-06-12 15:52:00+00:00         67    31.3     66.0     1002.5
11813 2026-06-12 15:53:00+00:00         66    31.3     67.0     1002.4
11814 2026-06-12 15:54:00+00:00         68    31.3     67.0     1002.4
11815 2026-06-12 15:55:00+00:00         68    31.3     67.0     1002.4
11816 2026-06-12 15:56:00+00:00         68    31.3     66.0     1002.4

[11817 rows x 5 columns]}

In [ ]:

pm_df = atmotube_device_weatherpm["pm"]
weather_df = atmotube_device_weatherpm["weather"]

use(atmotube_device_weatherpm)

In [ ]:
from src.utils import get

# d. Retrieve a specific variable 
atmotube_device_two_pms = get(data, "Atmotube", "C7A595F09965_01-May-2026_12-Jun-2026", ["pm"], ["pm2_5_ugm3_atm", "pm10_ugm3_atm"])

print(atmotube_device_two_pms)

The function `use()` can return a usable dataframe ready for analysis.

In [ ]:
from src.utils import use

use(atmotube_device) # merges all dataframes in one device, returns a ready-to-use table

use(atmotube_device)

,datetime,longitude,latitude,timezone,altitude,pm1_0_ugm3_atm,pm2_5_ugm3_atm,pm10_ugm3_atm,aqs_total,temp_c,...,tvoc_ppm,nox_index,co2_ppm,battery_phone_pct,motion_phone_bool,gps_phone_bool,charge_phone_bool,cooldown_phone_bool,position_error_m,user_notes
0,2026-05-30 14:57:00+00:00,NaN,NaN,<NA>,NaN,16.3,17.1,17.1,76,31.5,...,0.093,1.0,691.0,24,False,<NA>,False,False,NaN,NaN
1,2026-05-30 14:58:00+00:00,88.35042,22.50010,Asia/Kolkata,0.0,14.8,15.6,15.6,74,31.6,...,0.093,1.0,734.0,24,True,True,False,False,9.0,NaN
2,2026-05-30 14:59:00+00:00,88.35043,22.50008,Asia/Kolkata,0.0,15.6,16.4,16.4,74,31.5,...,0.095,1.0,727.0,24,True,True,False,False,7.0,NaN
3,2026-05-30 15:00:00+00:00,88.35045,22.50014,Asia/Kolkata,0.0,14.7,15.4,15.4,74,31.5,...,0.145,1.0,718.0,24,True,True,False,False,8.0,NaN
4,2026-05-30 15:01:00+00:00,88.35052,22.50025,Asia/Kolkata,0.0,17.5,18.4,18.4,75,31.4,...,0.181,1.0,706.0,24,True,True,False,False,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11812,2026-06-12 15:52:00+00:00,NaN,NaN,<NA>,NaN,27.9,29.2,29.2,67,31.3,...,0.071,1.0,504.0,38,False,<NA>,False,False,NaN,NaN
11813,2026-06-12 15:53:00+00:00,NaN,NaN,<NA>,NaN,28.7,30.1,30.1,66,31.3,...,0.070,1.0,530.0,38,False,<NA>,False,False,NaN,NaN
11814,2026-06-12 15:54:00+00:00,NaN,NaN,<NA>,NaN,27.2,28.5,28.5,68,31.3,...,0.074,1.0,836.0,37,False,<NA>,False,False,NaN,NaN
11815,2026-06-12 15:55:00+00:00,NaN,NaN,<NA>,NaN,26.5,27.8,27.8,68,31.3,...,0.076,1.0,646.0,37,False,<NA>,False,False,NaN,NaN
11816,2026-06-12 15:56:00+00:00,NaN,NaN,<NA>,NaN,26.5,27.9,28.0,68,31.3,...,0.074,1.0,632.0,37,False,<NA>,False,False,NaN,NaN

### Select for DataFrames or Variables

In [ ]:
from src.utils import get

                       datetime  pm1_0_ugm3_atm  pm2_5_ugm3_atm  pm10_ugm3_atm
0     2026-05-30 14:57:00+00:00            16.3            17.1           17.1
1     2026-05-30 14:58:00+00:00            14.8            15.6           15.6
2     2026-05-30 14:59:00+00:00            15.6            16.4           16.4
3     2026-05-30 15:00:00+00:00            14.7            15.4           15.4
4     2026-05-30 15:01:00+00:00            17.5            18.4           18.4
...                         ...             ...             ...            ...
11812 2026-06-12 15:52:00+00:00            27.9            29.2           29.2
11813 2026-06-12 15:53:00+00:00            28.7            30.1           30.1
11814 2026-06-12 15:54:00+00:00            27.2            28.5           28.5
11815 2026-06-12 15:55:00+00:00            26.5            27.8           27.8
11816 2026-06-12 15:56:00+00:00            26.5            27.9           28.0

[11817 rows x 4 columns]
0        17.1
1        15.6
2        16.4
3        15.4
4        18.4
         ...
11812    29.2
11813    30.1
11814    28.5
11815    27.8
11816    27.9
Name: pm2_5_ugm3_atm, Length: 11817, dtype: float64